---
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-5.10

- name: centos-6.6

- name: ubuntu-10.04
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[memcached::default]
  - name: instance
    run_list:
      - recipe[fake::instance]
