driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: fedora-21
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: fake::default
  - name: create
    run_list: fake::create
