AllCops:
  Exclude:
    - vendor/**/*
    - Guardfile

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
SingleSpaceBeforeFirstArg:
  Enabled: false
