# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# Shamelessly ripped from Active Support core_ext. Need a better solution. Later.
class Hash
  def deep_merge(other_hash, &block)
    dup.deep_merge!(other_hash, &block)
  end

  def deep_merge!(other_hash, &block)
    other_hash.each_pair do |current_key, other_value|
      this_value = self[current_key]

      self[current_key] = if this_value.is_a?(Hash) && other_value.is_a?(Hash)
        this_value.deep_merge(other_value, &block)
      else
        if block_given? && key?(current_key)
          block.call(current_key, this_value, other_value)
        else
          other_value
        end
      end
    end

    self
  end
end

settings = YAML.load_file 'vagrant.yml'

REQUIRED_PLUGINS = %w( vagrant-vbguest vagrant-berkshelf vagrant-omnibus vagrant-triggers)
PASSWORD_ERROR_MESSAGE = "You need to set your postgresql password in vagrant.yml to something other than 'password'"

def missing_plugins
  @missing_plugins ||= REQUIRED_PLUGINS.reject { |plugin| Vagrant.has_plugin? plugin }
end

def missing_multiple_plugins?
  missing_plugins.size > 1
end

if missing_plugins.any?
  puts "The following plugin#{'s' if missing_multiple_plugins?} are required: #{missing_plugins.join(" ")}"
  puts "Install #{missing_multiple_plugins? ? 'them' : 'it'} with this command: 'vagrant plugin install #{missing_plugins.join(" ")}'"
end

fail 'Required Vagrant plugins not installed. Please install before continuing' if missing_plugins.any?

fail PASSWORD_ERROR_MESSAGE if settings['postgresql']['password'] == 'password'

project_name = settings['project']['name']
postgresql_username = settings['postgresql']['username']
postgresql_password = settings['postgresql']['password']
forwarded_ports = settings['forwarded_ports'] || { :"3000" => 3000 }
vagrant_cpu_count = settings.fetch('vm', {}).fetch('cpu_count', 2)
vagrant_memory_size = settings.fetch('vm', {}).fetch('memory_size', '4096').to_s

chef_json = JSON.parse(File.read('vagrant.json'))

Vagrant.configure(2) do |config|
  # Prevent problematic caching of synced folders
  def remove_synced_folders_file(*_args)
    `rm .vagrant/machines/default/virtualbox/synced_folders`
  end

  config.trigger.before [:reload], stdout: true, &method(:remove_synced_folders_file)
  config.trigger.after [:halt], stdout: true, &method(:remove_synced_folders_file)

  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = 'ubuntu/trusty64'

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder '.', "/home/vagrant/#{project_name}"

  config.vbguest.auto_update = true

  config.vm.provider :virtualbox do |vb|
    vb.memory = vagrant_memory_size
    vb.cpus = vagrant_cpu_count
  end

  forwarded_ports.each do |guest_port, host_port|
    config.vm.network :forwarded_port, guest_ip: '0.0.0.0', guest: guest_port, host: host_port, autocorrect: true
  end

  config.ssh.forward_agent = true

  config.omnibus.chef_version = '12.0.3'
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['cookbooks', 'site-cookbooks', 'berks-cookbooks']

    chef.add_recipe 'apt'

    chef.json = {
      apt: {
        compiletime: true
      }
    }
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['cookbooks', 'site-cookbooks', 'berks-cookbooks']

    chef.add_recipe 'apt'
    chef.add_recipe 'build-essential'
    chef.add_recipe 'imagemagick'
    chef.add_recipe 'nodejs'
    chef.add_recipe 'ruby_build'
    chef.add_recipe 'rbenv::user'
    chef.add_recipe 'rbenv::vagrant'
    chef.add_recipe 'postgresql::ruby'
    chef.add_recipe 'postgresql::contrib'
    chef.add_recipe 'postgresql::server'
    chef.add_recipe 'postgresql::client'
    chef.add_recipe 'redisio'

    chef.json = chef_json.deep_merge({
      "postgresql" => {
        pg_hba: [
          {
            type: "local",
            db: "all",
            user: postgresql_username,
            method: "trust"
          },
          {
            type: "host",
            db: "all",
            user: postgresql_username,
            addr: "127.0.0.1/32",
            method: "trust"
          }
        ],
      },
      "run_list" => %w[
        recipe[postgresql::contrib]
        recipe[postgresql::server]
        recipe[redisio]
        recipe[redisio::enable]
      ]
    })
  end

  user_creation_plsql = <<-SCRIPT_SQL
    DO
      \\\\$\\\\$
      BEGIN
        IF NOT EXISTS (
          SELECT * FROM pg_catalog.pg_user WHERE usename = '#{postgresql_username}'
        )
        THEN CREATE USER #{postgresql_username} WITH CREATEDB LOGIN PASSWORD '#{postgresql_password}';
        END IF;
      END
      \\\\$\\\\$
    ;
  SCRIPT_SQL

  setup_postgres_script = <<-SCRIPT
    echo '===== Creating PostgreSQL databases and users'
    su postgres -c "psql -c \\"#{user_creation_plsql}\\""
  SCRIPT

  change_ssh_directory_script = <<-SCRIPT
    if [ $(pwd) != "~/#{project_name}" ]; then
      echo "cd ~/#{project_name}" >> ~/.profile
    fi
  SCRIPT

  add_redis_to_startup = <<-SCRIPT
    chown -R vagrant /home/vagrant/.rbenv
    sudo update-rc.d redis6379 defaults
    sudo service redis6379 start
  SCRIPT

  initialize_rails_app = <<-SCRIPT
    echo 'Bundling...'
    cd /home/vagrant/#{project_name}
    bundle
    rbenv rehash
    echo 'Creating DB'
    rake db:create
    echo 'Loading Schema'
    PGPASSWORD=#{postgresql_password} psql -U #{postgresql_username} infinity_erp < infinity_erp.sql
  SCRIPT

  privileged_initialize_script = <<-SCRIPT
    #!/bin/bash

    if [ ! -f ~/.privileged_initialized ]
    then
      #{add_redis_to_startup}
      touch ~/.privileged_initialized
    fi
  SCRIPT

  unprivileged_initialize_script = <<-SCRIPT
    #!/bin/bash

    if [ ! -f ~/.unprivileged_initialized ]
    then
      #{initialize_rails_app}
      touch ~/.unprivileged_initialized
    fi
  SCRIPT

  config.vm.provision :shell, name: 'Setup Postgresql', inline: setup_postgres_script
  config.vm.provision :shell, name: 'Privileged Initialization', inline: privileged_initialize_script
  config.vm.provision :shell, privileged: false, name: 'Unprivileged Initialization', inline: unprivileged_initialize_script
  config.vm.provision :shell, name: 'Setup Home Directory', privileged: false, inline: change_ssh_directory_script
end
